
spring:
  application:
    name: memoryBox_main
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_SERVER:localhost}:${DB_PORT:3306}/${DB_NAME:memorybox}?useUnicode=true&characterEncoding=utf-8
    #url: jdbc:mysql://${DB_SERVER:165.192.105.57}:${DB_PORT:31380}/${DB_NAME:mydb}?useUnicode=true&characterEncoding=utf-8
    #username: ${DB_USERNAME:root}
    #password: ${DB_PASSWORD:P@ssw0rd$}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
      minimum-idle: 2
      connection-test-query: SELECT 1

#swagger
springdoc:
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger.html
    enabled: true
    operationsSorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true    #try it out ?? ? request duration ? ??? ???
    doc-expansion : none    # api?? ?? ???
  #    groups-order: DESC
  api-docs:
    enabled: true
    path: /api-docs