kind: Deployment
apiVersion: apps/v1
metadata:
  name: memorybox-main
  labels:
    app: memorybox-main
spec:
  selector:
    matchLabels:
      app: memorybox-main
  replicas: 1
  template:
    metadata:
      name: memorybox-main
      labels:
        app: memorybox-main
    spec:
      containers:
        - name: memorybox-main
          image: docker.io/hyeonkyo/memorybox-main:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
          envFrom:
            - configMapRef:
                name: memorybox-cm
            - secretRef:
                name: memorybox-secret
          ports:
            - name: port1
              containerPort: 8081
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi
          volumeMounts:
            - name: image-data
              mountPath: /root/data
              readOnly: false
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
      volumes:
        - name: image-data
          persistentVolumeClaim:
            claimName: memory-box
            readOnly: false

---

apiVersion: v1
kind: Service
metadata:
  name: memorybox-main
spec:
  type: ClusterIP
  selector:
    app: memorybox-main
  ports:
    - name: memorybox-main
      port: 8080
      targetPort: 8080
